---
# tasks file for Docker

- name: Remove Docker if installed from Debian repo 
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install requirements
  apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install docker and its dependecies
  apt: 
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: yes

- name: Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Start the Docker daemon
  systemd:
    name: docker
    state: started
    masked: no

- name: Add debian user to docker group
  user:
    name: administrateur
    group: docker

- name: Download and Install Docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 'a+x'
  when: >
        docker_compose_current_version is not defined
        or docker_compose_current_version is version(docker_compose_version, '<')

- name: Install pip3 with python3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install pip Docker
  pip:
    name: 
      - docker
      - docker-compose
    state: present